### ISSUE TITLE
Want to install mesa-hw

### ISSUE THREAD

**Issue by anonimo82** [suhan-paradkar/tewmux-disabled#13]
Hello everyone.
I can't figure out what's the command to download and install package tagged mesa-hw, plus I tried the instructions in allchangesmade.txt, but I got stuck somewhere in the middle of the process.

Please, can you help?

Edit: My goal is to have hw acceleration in Termux - Andronix

**Comment by anonimo82** [comment]
@suhan-paradkar help, please

**Comment by DLC01** [comment]
what exactly was the issue you encountered?

**Comment by anonimo82** [comment]
I get error: "ERROR: Dependency "libdrm_nouveau" not found, tried pkgconfig and cmake"
When doing meson in folder mesa

**Comment by DLC01** [comment]
seems like the patch for mesa didn't properly apply 
try using `git apply <path to patch>`

**Comment by anonimo82** [comment]
The file tells to do:
git checkout b8970120545b3cb250821013cb459bf4d2acfda4

**Comment by DLC01** [comment]
there is an line after it saying to apply the patches

**Comment by anonimo82** [comment]
Where is the patch path?

**Comment by DLC01** [comment]
the patches should be in the respective directory in the patches folder

**Comment by anonimo82** [comment]
Which patch should I apply for the xorg-xserver-1.20.13 folder?

**Comment by anonimo82** [comment]
There are many

**Comment by DLC01** [comment]
this should be it
`for a in <path to the instructions folder>/patches/xorg/*.patch; do patch -p1 < "$a"`

**Comment by anonimo82** [comment]
I get a > prompt, what am I missing?

**Comment by anonimo82** [comment]
Ok, solved

**Comment by anonimo82** [comment]
Now, when building xorg, I get

^                                    1 error generated.
make[1]: *** [Makefile:822: xf86bigfont.lo] Error 1     make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/data/data/com.termux/files/home/dir/xorg-server-1.20.13/Xext'
make: *** [Makefile:820: install-recursive] Error 1

**Comment by anonimo82** [comment]
Ok, built all, just the last step ends with:

~ $ XDG_RUNTIME_DIR=$TMPDIR $PREFIX/bin/Xwayland &      [2] 8468
~ $ could not connect to wayland server                 (EE)
Fatal server error:                                     (EE) Couldn't add screen                                (EE)                                                                                                            [2]-  Exit 1                  XDG_RUNTIME_DIR=$TMPDIR $PREFIX/bin/Xwayland

**Comment by DLC01** [comment]
you need to start the termux-x11 first before running Xwayland

**Comment by anonimo82** [comment]
How?

**Comment by anonimo82** [comment]
I'm using XServer XSDL

**Comment by anonimo82** [comment]
@DLC01 help?

**Comment by DLC01** [comment]
> I'm using XServer XSDL

it will not work in XSDL as far as i know

**Comment by anonimo82** [comment]
Ok, so, what do I need to do?

**Comment by DLC01** [comment]
> How?

install both the .deb(in termux) and the apk from [here](https://github.com/termux/termux-x11/releases/tag/1.02.06) then you can follow the rest of the instructions on how to run an gui environment from [here](https://github.com/termux/termux-x11#running-graphical-applications)

**Comment by anonimo82** [comment]
Ok, solved this all.
I get very poor performance by the way

**Comment by DLC01** [comment]
> Ok, solved this all. I get very poor performance by the way

an potential reason for that would be when installing the deb the Xwayland executable that you compiled may have been replaced by the one in the repo, should be easy as going into the xorg directory and doing `make install` again and set GALLIUM_DRIVER=zink to make it use Zink

**Comment by DLC01** [comment]
mesa may also have been replaced by the one in the repo so do `ninja install` again in mesa's build director

**Comment by anonimo82** [comment]
It's weird, this time I get this after all files compiled:

raise RuntimeError(f'Destination {link!r} already exists and is not a symlink')
RuntimeError: Destination '/data/data/com.termux/files/usr/lib/libglapi.so' already exists and is not a symlink

ERROR: Unhandled python exception

    This is a Meson bug and should be reported!
FAILED: meson-install
/data/data/com.termux/files/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.

**Comment by DLC01** [comment]
try doing `ninja uninstall` first then do `ninja install`

**Comment by anonimo82** [comment]
Nope, doesn't work

**Comment by DLC01** [comment]
try removing the conflicting file with `rm` first then try again?

**Comment by anonimo82** [comment]
Succeeded

**Comment by anonimo82** [comment]
Now the benchmarks don't run

**Comment by DLC01** [comment]
did you reinstall xorg too?

**Comment by anonimo82** [comment]
No, sorry. Where should I add your option?

**Comment by DLC01** [comment]
cd to the directory where you compiled xorg-server and do `make install`

**Comment by anonimo82** [comment]
Yes, but where should I put your "GALLIUM_DRIVER=zink"?

**Comment by DLC01** [comment]
you can export it as en environment variable
`export GALLIUM_DRIVER=zink` or you can append it before the command you want to run  `GALLIUM_DRIVER=zink <your application>`

**Comment by anonimo82** [comment]
Thanks so much, now it's very smooth

**Comment by anonimo82** [comment]
Kudos and big thanks

**Comment by DLC01** [comment]
no problem :)
