### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by JesusChapman** [suhan-paradkar/tewmux-disabled#2]
@suhan-paradkar

No problem if I place these packages here ? :  

https://github.com/Yisus7u7/pkgs.yisus.org

Obviously, I'll leave credits.

**Comment by creepy-pasta101** [comment]
@Yisus7u7 yeah it's fine....
currently @leapofazzam123 is also hosting my packages [here](https://github.com/leapofazzam123/termux-plus)

Also, you can build those packages from build scripts located [here](https://github.com/suhan-paradkar/my-tewmux-build-config)

**Comment by JesusChapman** [comment]
@suhan-paradkar I remind you that I don't have a pc, I can't compile them  :C

**Comment by creepy-pasta101** [comment]
> @suhan-paradkar I remind you that I don't have a pc, I can't compile them :C

Even I don't have a PC ... use gcloud.....
See @kcubeterm 's gist....

**Comment by JesusChapman** [comment]
Already e seen the profile of the above, which is gcloud?

**Comment by creepy-pasta101** [comment]
> Already e seen the profile of the above, which is gcloud? 

Here goes....
https://gist.github.com/kcubeterm/7e2792366bd6e8c14064f7e2ac109cc7

**Comment by JesusChapman** [comment]
Ohhh, awesome

**Comment by creepy-pasta101** [comment]
Also... you can press the watch button above.... so that you can get updates  whenever I release a new package
