### ISSUE TITLE
Wayland question 

### ISSUE THREAD

**Issue by JesusChapman** [suhan-paradkar/tewmux-disabled#3]
Good evening, I heard that wayland is a protocol for desktops, is there any way to use it with vnc? Or how to use the package

**Comment by creepy-pasta101** [comment]
> Good evening, I heard that wayland is a protocol for desktops, is there any way to use it with vnc? Or how to use the package

You can use it with termux-x11 app

**Comment by JesusChapman** [comment]
Where do I get it?, please

**Comment by creepy-pasta101** [comment]
Here goes....
https://github.com/suhan-paradkar/termux-x11/actions/runs/941754040

**Comment by creepy-pasta101** [comment]
@Yisus7u7 You need to reinstall termux to debug variant.... From github actions..

**Comment by JesusChapman** [comment]
What do I do with that file?

**Comment by JesusChapman** [comment]
I got an application installation error

**Comment by creepy-pasta101** [comment]
> I got an application installation error 

As I said.... Reinstall termux to debug version...

**Comment by JesusChapman** [comment]
Oh ok

**Comment by JesusChapman** [comment]
I already did, it still won't let me install it

**Comment by JesusChapman** [comment]
Already delete the app of termux and do not let me install it

**Comment by creepy-pasta101** [comment]
> Already delete the app of termux and do not let me install it

Could you install termux?? Debug artifact??

**Comment by creepy-pasta101** [comment]
If no... Then uninstall all termux modules

**Comment by JesusChapman** [comment]
Ok Hold on

**Comment by JesusChapman** [comment]
I continue with the error

**Comment by JesusChapman** [comment]
I installed again termux and not open it, installing termux x11 does not let me

**Comment by creepy-pasta101** [comment]
Can you try installing it using SAI... Available at playstore... And send me debug info....

**Comment by JesusChapman** [comment]
Error :  
```
INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package couldn't be installed in /mnt/expand/4f57ba67-c414-45b0-834c-f1985bacf4fc/app/com.termux.x11-mVI1IUhhTCdWfDxz2CLe9A==: Package com.termux.x11 has no signatures that match those in shared user com.termux; ignoring!
```

**Comment by JesusChapman** [comment]
@suhan-paradkar?

**Comment by creepy-pasta101** [comment]
> @suhan-paradkar? 

Install termux from here.....
https://github.com/termux/termux-app/suites/3130709259/artifacts/71807415

**Comment by JesusChapman** [comment]
Ok

**Comment by creepy-pasta101** [comment]
> > @suhan-paradkar? 
> 
> Install termux from here.....
> https://github.com/termux/termux-app/suites/3130709259/artifacts/71807415

This here.... Is the debug artifact..... What I said earlier

**Comment by JesusChapman** [comment]
Error

INSTALL_FAILED_SHARED_USER_INCOMPATIBLE: Package couldn't be installed in /mnt/expand/4f57ba67-c414-45b0-834c-f1985bacf4fc/app/com.termux-PssIm_Kp1bhgwfBj3TH1ng==: Package com.termux has no signatures that match those in shared user com.termux; ignoring!

**Comment by JesusChapman** [comment]
:(

**Comment by JesusChapman** [comment]
Ya!!!, make it

**Comment by JesusChapman** [comment]
What should I do now?

**Comment by creepy-pasta101** [comment]
> Ya!!!, make it 

@Yisus7u7 Installed??

**Comment by JesusChapman** [comment]
Yes

**Comment by JesusChapman** [comment]
Installed yes

**Comment by creepy-pasta101** [comment]
Now open the app and acquire wakelock...

**Comment by JesusChapman** [comment]
ready

**Comment by creepy-pasta101** [comment]
Do you have xwayland deb installed?? 
If no ... Install it and then run 
```
export XDG_RUNTIME_DIR=$PREFIX/tmp
```
and then
```
Xwayland -ac :1 &
```

And atlast....
```
xfce4-session --display=:1 &
```
Or any DE of your choice

**Comment by JesusChapman** [comment]
Okay

**Comment by creepy-pasta101** [comment]
Now open termux-x11... And ta-da

**Comment by JesusChapman** [comment]
![Screenshot_20210701-031500](https://user-images.githubusercontent.com/64093255/124090581-95abc800-da1a-11eb-989f-3fd9e1da84f4.png)

**Comment by JesusChapman** [comment]
Is there a way to use it by vnc?, do you feel uncomfortable that way

**Comment by creepy-pasta101** [comment]
You can use lxqt.. if you want....

**Comment by JesusChapman** [comment]
I'm using xfce4, but it feels uncomfortable

**Comment by creepy-pasta101** [comment]
> Is there a way to use it by vnc?, do you feel uncomfortable that way 

I reconfigured it this way... So I am pretty comfortable with it..

![Screenshot_2021-07-01-13-47-35-78.jpg](https://user-images.githubusercontent.com/76830230/124091045-0d0d4600-da73-11eb-914c-0bdf542219b3.jpg)

I may compile xwayland vnc backend soon.. If I have time...

**Comment by JesusChapman** [comment]
How do I give clik right?

**Comment by creepy-pasta101** [comment]
Its direct mode...

**Comment by creepy-pasta101** [comment]
If you want to use other methods.... You can got to preferences in your notification panel and configure input method there

**Comment by creepy-pasta101** [comment]
> How do I give clik right? 

You mean right click??

**Comment by JesusChapman** [comment]
Yeah

**Comment by JesusChapman** [comment]
How?

**Comment by creepy-pasta101** [comment]
> How? 

See this for basic operations...

https://user-images.githubusercontent.com/76830230/124092788-db957a00-da74-11eb-87d0-cf0ea66cd551.mp4

Well.. since it is forked from abandoned termux-x11... Right click is not well implemented...

**Comment by JesusChapman** [comment]
If this, just click slightly with both fingers

**Comment by JesusChapman** [comment]
I was referring to the right click on termux:x11..

**Comment by creepy-pasta101** [comment]
> 
> 
> I was referring to the right click on termux:x11..

Thats what... its not implemented

**Comment by yitaverse** [comment]
> 
> 
> Do you have xwayland deb installed??
> If no ... Install it and then run
> 
> ```
> export XDG_RUNTIME_DIR=$PREFIX/tmp
> ```
> 
> and then
> 
> ```
> Xwayland -ac :1 &
> ```
> 
> And atlast....
> 
> ```
> xfce4-session --display=:1 &
> ```
> 
> Or any DE of your choice

Hello @suhan-paradkar, thank you so much for all these instructions that I'm following in this discussion, after seen the [marvelous video](https://www.reddit.com/r/termux/comments/oc1pbc/termux11_app_xwayland/) of @Yisus7u7. It's still not clear to me if the _xfce4_ linux desktop environment of @Yisus7u7's video is installed on Android device or if it's just projected on it... 

I'm arrived in this step where you were asking to @Yisus7u7 if the `xwayland` deb package was installed... I would to know if I have to install it on my linux machine or on Android, and in this last case I tried with `apt-get` or `pkg` into Termux but I found no package available in Termux... I found [this repository](https://github.com/sfdroid/android_external_wayland) on GitHub instead, and so I'm wondering if I have to run those build instructions in Termux to install `wayland` and so to proceed with your next steps, always in Termux on Android... I found also these [[1](https://wayland.freedesktop.org/xserver.html)][[2](https://wayland.freedesktop.org/building.html)] other pages. Thanks for the clarification! 

Cheers

**Comment by creepy-pasta101** [comment]
@ChemBioScripting You need to install it in the machine whose gui output you desire... On linux... Simple apt-get install works... But for termux... Use the deb package provided on the releases section of this repository

**Comment by yitaverse** [comment]
> 
> 
> @ChemBioScripting You need to install it in the machine whose gui output you desire... On linux... Simple apt-get install works... But for termux... Use the deb package provided on the releases section of this repository

@suhan-paradkar, thank you so much for your reply! I use the Fedora distro; I will try to install `xwayland` (`sudo dnf install xwayland`), but about the last thing you said about the _.deb_ package provided in the releases section of your repository, I found only [this package](https://github.com/suhan-paradkar/tewmux-disabled/releases/tag/Jadx), _jadx-0.6.1_all.deb_... Looking for [info about jadx](https://www.secplicity.org/2019/10/04/android-apk-reverse-engineering-using-jadx/), it would appear to be a _reverse engineering program_... I thought you were referring to an _equivalent of xwayland for Android_ via Termux, to be installed with `apt-get install ./jadx-0.6.1_all.deb` in Termux... Thanks for your support!

Cheers

**Comment by Yisus7u7** [comment]
The package is available, run the installation brief here:

https://pkgs-termux.github.io/pkgs.org

And then run:

pkg install xwayland

**Comment by JesusChapman** [comment]
@suhan-paradkar Why did you delete your repository?, your version of termux wayland had full screen mode, the one provided by termux now does not, and I need that mode.

**Comment by creepy-pasta101** [comment]
I didn't delete it.. I transferred the ownership to @WMCB-Tech and all changes are now merged upstream

**Comment by JesusChapman** [comment]
> No lo eliminé ... Transferí la propiedad a @ WMCB-Tech y todos los cambios ahora se fusionaron en sentido ascendente

He eliminated the releases .

**Comment by ghost** [comment]
> 
> 
> > No lo eliminé ... Transferí la propiedad a @ WMCB-Tech y todos los cambios ahora se fusionaron en sentido ascendente
> 
> He eliminated the releases .

@Yisus7u7 Releases are in my drive for later use, however apks are available in the debug artifacts in upstream so there's no point keeping it to an extent

**Comment by JesusChapman** [comment]
> > > No lo eliminé ... Transferí la propiedad a @ WMCB-Tech y todos los cambios ahora se fusionaron en sentido ascendente
> > 
> > 
> > He eliminated the releases .
> 
> @Yisus7u7 Releases are in my drive for later use, however apks are available in the debug artifacts in upstream so there's no point keeping it to an extent

I downloaded them and none bring the full screen option. 

The most recent ones have many bugs with the full-screen option.

**Comment by thunder-coding** [comment]
Locking the conversation back to collaborators since the termux-x11 app has moved to github.com/termux/termux-x11.

Any bug reports for the x11 application **should** be done in github.com/termux/termux-x11/issues

Any other kind of support/off-topic talks for the **Termux X11** app should be limited to the [Termux community page](https://wiki.termux.com/wiki/Community) and [GitHub discussions in termux/termux-x11](https://github.com/termux/termux-x11)
