### ISSUE TITLE
Wayland error

### ISSUE THREAD

**Issue by JesusChapman** [suhan-paradkar/tewmux-disabled#4]
![Screenshot_20210803-145356](https://user-images.githubusercontent.com/64093255/128077594-db5dd5cb-b435-4324-9139-0d98a09ac542.png)

**Comment by creepy-pasta101** [comment]
Thats a problem after libffi has been bumped.... 
I have replaced the debs, which now work fine....
You can download it from the same location as of the old debs

**Comment by JesusChapman** [comment]
Thanks
