### ISSUE TITLE
xorg-server ask 

### ISSUE THREAD

**Issue by spz0622** [suhan-paradkar/tewmux-disabled#5]
Hello 
and what it can do

**Comment by creepy-pasta101** [comment]
What do you want to ask??

**Comment by spz0622** [comment]
xorg-server

**Comment by creepy-pasta101** [comment]
It is a local server to which gtk windows are rendered

**Comment by creepy-pasta101** [comment]
And please don't ask basic questions here...
Please google them out yourself

**Comment by spz0622** [comment]
im test 
but
X -ac -screen 800x480 :1                                                ─╯
InitConnectionLimits: MaxClients = 2048
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE)
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
(EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
(EE) Please also check the log file at "/data/data/com.termux/files/home/.local/share/xorg/Xorg.1.log" for additional information.
(EE)
(EE) Server terminated with error (1). Closing log file.

**Comment by spz0622** [comment]
and
vncserver -list                                                         ─╯

TigerVNC server sessions:

X DISPLAY #     PROCESS ID
:1              10318

**Comment by creepy-pasta101** [comment]
```
pkill 10318
```
And try again... mostly a background process was already running

**Comment by spz0622** [comment]
not

?????? ?? ?? ?? ~ ??                                              ?? ?? ?? 21:19:48 ?? ??????
???? 10318                                                                     ????
10318: command not found
?????? ?? ?? ?? ~ ??                                          ?? 127 ?? ?? 21:19:58 ?? ??????
???? pkill 10318                                                               ????
?????? ?? ?? ?? ~ ??                                            ?? 1 ?? ?? 21:20:03 ?? ??????
???? X -ac -screen 800x480 :1.0                                                ????
InitConnectionLimits: MaxClients = 2048
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: server already running
(EE) 
Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/data/data/com.termux/files/home/.local/share/xorg/Xorg.1.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
?????? ?? ?? ?? ~ ??                                            ?? 1 ?? ?? 21:20:27 ?? ??????
????                                                                           ????
im in xfce-terminal
