### ISSUE TITLE
i386 Build

### ISSUE THREAD

**Issue by akbarri** [suhan-paradkar/tewmux-disabled#6]
Is there any changes for i386 Build?
libwayland-protocols_1.17-4_i386.deb
libwayland_1.19.0_i386.deb
xwayland_1.20.5-6_i386.deb

![Screenshot_20210811-115853_Termux](https://user-images.githubusercontent.com/72637686/128974552-1ee38a2f-56ff-4a7f-9b27-1f3e650b67ce.jpg)

**Comment by creepy-pasta101** [comment]
Can you try it after you installed xfce4 ??

**Comment by akbarri** [comment]
XFCE4 already installed before.
No Issue with VNC on i386 Env.
I wanna try Wayland but package for i386 N/A.

**Comment by creepy-pasta101** [comment]
Looks like one of the above mentioned packages is causing a conflict...

**Comment by akbarri** [comment]
Your Build Packages is i686 not i386.
Pictures Above try to install i686 packages on i386 Env.

**Comment by akbarri** [comment]
Solved, using Xwayland from ubuntu port instead.
![Screenshot_20210814-195337_TermuxWayland](https://user-images.githubusercontent.com/72637686/129446967-5948da12-cddd-4b49-883c-199299aab583.jpg)
Cheers,
Thank You for your Hardwork 🙏🏻
