### ISSUE TITLE
Termux Wayland

### ISSUE THREAD

**Issue by TheUnknownPeople-user** [suhan-paradkar/tewmux-disabled#8]
I want to download your Termux Wayland but the repository is no longer accessible, how can I download the Termux Wayland?

**Comment by suhan-paradkar** [comment]
Its already there in the official repos as of now.. just do `pkg i x11-repo && pkg i xwayland`

**Comment by suhan-paradkar** [comment]
Its now shifted upstream https://github.com/termux/termux-x11

**Comment by TheUnknownPeople-user** [comment]
> Its now shifted upstream https://github.com/termux/termux-x11

How To Use And Install Termux-x11?
